### ISSUE TITLE
Issue with font cascading

### ISSUE THREAD

**Issue by Jiropole** [dreamwieber/AttributedMarkdown#35]
I have some simple markdown that just uses paragraph and strong styles. When your library generates the attributed string, the color of the strong style is correct, but instead of using the font I specified for STRONG, I get the standard paragraph font. Below are some logs to help clarify what I'm seeing. Any thoughts are appreciated, and thanks for the library.

**(lldb) po paragraphAttributes**
{
    NSColor = "UIDeviceRGBColorSpace 0 0.294118 0.529412 1";
    NSFont = "<UICTFont: 0x7b65e4e0> font-family: \"Effra-Light\"; font-weight: normal; font-style: normal; font-size: 21.00pt";
}

**(lldb) po strongAttributes**
{
    NSColor = "UIDeviceRGBColorSpace 1 1 1 1";
    NSFont = "<UICTFont: 0x7b6402e0> font-family: \"Effra-Medium\"; font-weight: normal; font-style: normal; font-size: 21.00pt";
}

            attributes[@(PARA)] = paragraphAttributes;
            attributes[@(STRONG)] = strongAttributes;
            NSString *rawText = @"This is regular paragraph text **and this is strong.**";

**(lldb) po attributedString**
This is regular paragraph text {
    NSColor = "UIDeviceRGBColorSpace 0 0.294118 0.529412 1";
    NSFont = "<UICTFont: 0x7b65e4e0> font-family: \"Effra-Light\"; font-weight: normal; font-style: normal; font-size: 21.00pt";
}and this is strong. {
    NSColor = "UIDeviceRGBColorSpace 1 1 1 1";
    NSFont = "<UICTFont: 0x7b65e4e0> font-family: \"Effra-Light\"; font-weight: normal; font-style: normal; font-size: 21.00pt";
}

**Comment by dreamwieber** [comment]
Thanks! I'll investigate...

**Comment by Jiropole** [comment]
My test case is very simple; just using a different font for spanned styles than used at the paragraph level. Is it possible I'm doing something wrong? I gathered that one just had to set the attributes for each markdown style in use, but maybe I'm missing something.

**Comment by Jiropole** [comment]
My solution is to modify your markdown_output.m logic for cascading font styles to give precedence to the element font, if present, rather than the inherited font. In my version 0.5, this amounts to changing line 118 to base the new font on the element rather than inherited font:

 `CTFontRef outCTFont = CTFontCreateCopyWithSymbolicTraits(elementCTFont, ...`

I'll leave it to you whether this is the desirable, general behavior. In my mind, the element font familly should take precedence over the inherited family.

**Comment by dreamwieber** [comment]
Thanks for tracking this down. Want to submit a pull request?
